Replaced a stupid copy-paste mistake of the ^= operator from cppreference.com.
While copying the operators from http://en.cppreference.com/w/cpp/language/operators, the ^= is copied as ˆ=, which is *not* the same. Compiling that will give an error similar to this:

prog.cc:13:14: error: stray '\313' in program
 auto operatorˆ= (Args && ... args)
              ^
prog.cc:13:15: error: stray '\206' in program
 auto operatorˆ= (Args && ... args)